---
order: 1
---

# Agregering af data

## Detaljerede data

Til dataanalyse har man optimalt rådighed over data som beskriver enkeltbegivenheder. Hvert salg i en butik, hver enkelt transaktion i bank, hvert registrering af måledata, hver gang en tæller aktiveret, hver gang en handling udføres. Hver enkelt af alting. \
Det er den fineste detaljeringsgrad.

## Sammensæt resumerede data med Agregering

Ofte vil man gerne have sammensat oplysningerne på en af flere måder. Det kaldes aggregering. \
Agregeringsfunktionerne kan være *tælle* (count), *summering* (sum), *gennemsnit* (mean/avg), *minimum/maksimum* (min/max).\
Det er en mulighed at anvende agreringerne globat, så der bare returneres et tal; antallet af salg i hele butikkenshistorie, indestående på alle konti i banken osv.\
Det er også muligt at man ønsker agregering gruperet på data fra en anden kolonne eller felt i en post. F.eks hvor meget er derm omsat i hver filial af en butikskæde, hvor meget har hver sælger solgt for, hvor mange biler er kørt ind i anlæget, hvad er det højeste antal udlånte bøger på biblioteket, osv.

## Agregering i intervaller

Man kan gruppere på unikke værdier, men også på intervaller af værdier, f.eks. borgere med intægter 0-250.000, 250.000-500.000, 500.000-1.000.000, 1.000.000 eller mere.

## Agregering i intervaller i tid og dato

Tidsintevaller bruges ofte til at grupere data efter, f.eks. pr. time, pr dag. pr. måned eller år.
