project:
  title: "FAG_Pathon2"
  output-dir: output
  type: website

execute:
  freeze: auto

website:
  # reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Hjem
      # - about.qmd
  sidebar: 
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: da
  

  
  